### ISSUE TITLE
ThisBuild / crossScalaVersions results in error on project load

### ISSUE THREAD

**Issue by bpholt** [typelevel/sbt-typelevel#615]
Is it expected that using
```scala
ThisBuild / crossScalaVersions := Seq(Scala_2_12, Scala_2_13)
```
will result in this error on load?
```
java.util.NoSuchElementException
	at scala.collection.LinearSeqOptimized.last(LinearSeqOptimized.scala:150)
	at scala.collection.LinearSeqOptimized.last$(LinearSeqOptimized.scala:149)
	at scala.collection.immutable.List.last(List.scala:91)
	at org.typelevel.sbt.TypelevelSettingsPlugin$.$anonfun$globalSettings$3(TypelevelSettingsPlugin.scala:49)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:229)
	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:171)
	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:88)
	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:100)
	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:95)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[error] java.util.NoSuchElementException
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

Removing `ThisBuild / ` makes it work, but it's surprising that it matters:
```scala
crossScalaVersions := Seq(Scala_2_12, Scala_2_13)
```

This is the line in question: 

https://github.com/typelevel/sbt-typelevel/blob/9309a656f0f3b97dfe2650fb6a8c99362a958fea/settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala#L49

**Comment by armanbilge** [comment]
Hmm, no, that seems odd. Any chance you can link to the build?

**Comment by j-mie6** [comment]
my Scala cross versions are specified as:

```scala
inThisBuild(List(
   ...
   crossScalaVersions := Seq(Scala213, Scala212, Scala3),
   ...
)
```

Which I believe should be equivalent to what you had: it works fine on `RC9`.

**Comment by bpholt** [comment]
> Any chance you can link to the build?

Unfortunately this is an internal library so I can't share the build. I'll see if I can minimize.

> ```scala
> inThisBuild(List(
>   ...
>    crossScalaVersions := Seq(Scala213, Scala212, Scala3),
>    ...
> )
> ```

FWIW, I was under the impression that the `inThisBuild` macro has some subtle differences from the `ThisBuild` scope, so we've been moving things to use the scope directly. But in any event, in this build, I get the same `NoSuchElementException` using 
```scala
inThisBuild(List(
  crossScalaVersions := Seq(Scala_2_12, Scala_2_13)
))
```
(albeit with a lot of other settings still set using the scope directly)

**Comment by bpholt** [comment]
@armanbilge I was able to minimize; check out [this gist](https://gist.github.com/bpholt/eb746c2217b009fceeda2c78226988cc). tl;dr, it looks like it was caused by the root project explicitly setting `crossScalaVersions := Seq.empty`. (It did that to suppress publishing in the root project; I've since switched it to use the NoPublishPlugin instead.)

**Comment by bpholt** [comment]
This is stale; I'm closing it.
